# Copyright (c) 2023-2024 Antmicro <www.antmicro.com>
# SPDX-License-Identifier: Apache-2.0

image: debian:bookworm

include:
  - project: 'repositories/tristan-lpddr4-integration'
    ref: internal-ci
    file: '/internal.yml'
