# Copyright (C) 2023 Antmicro
# SPDX-License-Identifier: Apache-2.0

ips:
  dram_ctrl_inst:
    file: ../build/dram_ctrl/gateware/dram_ctrl.v
    module: dram_ctrl
  phy_core_inst:
    file: ../build/generated/gateware/phy_core.v
    module: phy_core
  lpddr4_soc_inst:
    file: ../build/generated/gateware/lpddr4_soc.v
    module: lpddr4_soc

design:
  ports:
    lpddr4_soc_inst:
      serial1_rx: serial1_rx

      wb_bus_dram_dat_r: [dram_ctrl_inst, user_port_wishbone_0_dat_r]
      wb_bus_dram_ack: [dram_ctrl_inst, user_port_wishbone_0_ack]
      wb_bus_dram_err: [dram_ctrl_inst, user_port_wishbone_0_err]

      wb_bus_ctrl_dat_r: [dram_ctrl_inst, wb_ctrl_dat_r]
      wb_bus_ctrl_ack: [dram_ctrl_inst, wb_ctrl_ack]
      wb_bus_ctrl_err: [dram_ctrl_inst, wb_ctrl_err]

    dram_ctrl_inst:
      clk: [lpddr4_soc, sys_clk]
      rst: [lpddr4_soc, sys_rst]

      wb_ctrl_adr: [lpddr4_soc, wb_ctrl_adr]
      wb_ctrl_dat_w: [lpddr4_soc, wb_ctrl_dat_w]
      wb_ctrl_sel: [lpddr4_soc, wb_ctrl_sel]
      wb_ctrl_cyc: [lpddr4_soc, wb_ctrl_cyc]
      wb_ctrl_stb: [lpddr4_soc, wb_ctrl_stb]
      wb_ctrl_we: [lpddr4_soc, wb_ctrl_we]
      wb_ctrl_cti: [lpddr4_soc, wb_ctrl_cti]
      wb_ctrl_bte: [lpddr4_soc, wb_ctrl_bte]

      user_port_wishbone_0_adr: [lpddr4_soc, wb_dram_adr]
      user_port_wishbone_0_dat_w: [lpddr4_soc, wb_dram_dat_w]
      user_port_wishbone_0_sel: [lpddr4_soc, wb_dram_sel]
      user_port_wishbone_0_cyc: [lpddr4_soc, wb_dram_cyc]
      user_port_wishbone_0_stb: [lpddr4_soc, wb_dram_stb]
      user_port_wishbone_0_we: [lpddr4_soc, wb_dram_we]

      dfi_init_complete: [phy_core_inst, dfi_init_complete]

      dfi_alert_n_w0: [phy_core_inst, dfi_alert_n_w0]
      dfi_rddata_w0: [phy_core_inst, dfi_rddata_w0]
      dfi_rddata_valid_w0: [phy_core_inst, dfi_rddata_valid_w0]

      dfi_alert_n_w1: [phy_core_inst, dfi_alert_n_w1]
      dfi_rddata_w1: [phy_core_inst, dfi_rddata_w1]
      dfi_rddata_valid_w1: [phy_core_inst, dfi_rddata_valid_w1]

      dfi_alert_n_w2: [phy_core_inst, dfi_alert_n_w2]
      dfi_rddata_w2: [phy_core_inst, dfi_rddata_w2]
      dfi_rddata_valid_w2: [phy_core_inst, dfi_rddata_valid_w2]

      dfi_alert_n_w3: [phy_core_inst, dfi_alert_n_w3]
      dfi_rddata_w3: [phy_core_inst, dfi_rddata_w3]
      dfi_rddata_valid_w3: [phy_core_inst, dfi_rddata_valid_w3]

      dfi_alert_n_w4: [phy_core_inst, dfi_alert_n_w4]
      dfi_rddata_w4: [phy_core_inst, dfi_rddata_w4]
      dfi_rddata_valid_w4: [phy_core_inst, dfi_rddata_valid_w4]

      dfi_alert_n_w5: [phy_core_inst, dfi_alert_n_w5]
      dfi_rddata_w5: [phy_core_inst, dfi_rddata_w5]
      dfi_rddata_valid_w5: [phy_core_inst, dfi_rddata_valid_w5]

      dfi_alert_n_w6: [phy_core_inst, dfi_alert_n_w6]
      dfi_rddata_w6: [phy_core_inst, dfi_rddata_w6]
      dfi_rddata_valid_w6: [phy_core_inst, dfi_rddata_valid_w6]

      dfi_alert_n_w7: [phy_core_inst, dfi_alert_n_w7]
      dfi_rddata_w7: [phy_core_inst, dfi_rddata_w7]
      dfi_rddata_valid_w7: [phy_core_inst, dfi_rddata_valid_w7]

external:
  ports:
    in:
      - clk100
      - serial1_rx
    out:
      - serial1_tx
