# Copyright (C) 2023-2024 Antmicro
# SPDX-License-Identifier: Apache-2.0

ips:
  dram_ctrl_inst:
    file: build/topwrap/gen_dram_ctrl.yaml
    module: dram_ctrl
  phy_core_inst:
    file: build/topwrap/gen_dram_phy.yaml
    module: dram_phy
  lpddr4_soc_inst:
    file: build/topwrap/gen_lpddr4_soc.yaml
    module: lpddr4_soc

design:
  ports:
    lpddr4_soc_inst:
      sys_clk: [phy_core_inst, clk_sys]
      sys_rst: [phy_core_inst, rst_sys]

      user_led0: user_led0
      user_led1: user_led1
      user_led2: user_led2
      user_led3: user_led3
      user_led4: user_led4

      serial1_rx: serial1_rx
      serial1_tx: serial1_tx

      wb_bus_dram_if_dat_r: [dram_ctrl_inst, user_port_wishbone_0_dat_r]
      wb_bus_dram_if_ack: [dram_ctrl_inst, user_port_wishbone_0_ack]
      wb_bus_dram_if_err: [dram_ctrl_inst, user_port_wishbone_0_err]

      wb_bus_ctrl_if_dat_r: [dram_ctrl_inst, wb_ctrl_dat_r]
      wb_bus_ctrl_if_ack: [dram_ctrl_inst, wb_ctrl_ack]
      wb_bus_ctrl_if_err: [dram_ctrl_inst, wb_ctrl_err]

    dram_ctrl_inst:
      clk: [lpddr4_soc_inst, sys_clk]
      rst: [phy_core_inst, rst_sys]

      wb_ctrl_adr: [lpddr4_soc_inst, wb_bus_ctrl_if_adr]
      wb_ctrl_dat_w: [lpddr4_soc_inst, wb_bus_ctrl_if_dat_w]
      wb_ctrl_sel: [lpddr4_soc_inst, wb_bus_ctrl_if_sel]
      wb_ctrl_cyc: [lpddr4_soc_inst, wb_bus_ctrl_if_cyc]
      wb_ctrl_stb: [lpddr4_soc_inst, wb_bus_ctrl_if_stb]
      wb_ctrl_we: [lpddr4_soc_inst, wb_bus_ctrl_if_we]
      wb_ctrl_cti: [lpddr4_soc_inst, wb_bus_ctrl_if_cti]
      wb_ctrl_bte: [lpddr4_soc_inst, wb_bus_ctrl_if_bte]

      user_port_wishbone_0_adr: [lpddr4_soc_inst, wb_bus_dram_if_adr]
      user_port_wishbone_0_dat_w: [lpddr4_soc_inst, wb_bus_dram_if_dat_w]
      user_port_wishbone_0_sel: [lpddr4_soc_inst, wb_bus_dram_if_sel]
      user_port_wishbone_0_cyc: [lpddr4_soc_inst, wb_bus_dram_if_cyc]
      user_port_wishbone_0_stb: [lpddr4_soc_inst, wb_bus_dram_if_stb]
      user_port_wishbone_0_we: [lpddr4_soc_inst, wb_bus_dram_if_we]

      dfi_init_complete: [phy_core_inst, dfi_init_complete]

      dfi_alert_n_w0: [phy_core_inst, dfi_alert_n_w0]
      dfi_rddata_w0: [phy_core_inst, dfi_rddata_w0]
      dfi_rddata_valid_w0: [phy_core_inst, dfi_rddata_valid_w0]

      dfi_alert_n_w1: [phy_core_inst, dfi_alert_n_w1]
      dfi_rddata_w1: [phy_core_inst, dfi_rddata_w1]
      dfi_rddata_valid_w1: [phy_core_inst, dfi_rddata_valid_w1]

      dfi_alert_n_w2: [phy_core_inst, dfi_alert_n_w2]
      dfi_rddata_w2: [phy_core_inst, dfi_rddata_w2]
      dfi_rddata_valid_w2: [phy_core_inst, dfi_rddata_valid_w2]

      dfi_alert_n_w3: [phy_core_inst, dfi_alert_n_w3]
      dfi_rddata_w3: [phy_core_inst, dfi_rddata_w3]
      dfi_rddata_valid_w3: [phy_core_inst, dfi_rddata_valid_w3]

      dfi_alert_n_w4: [phy_core_inst, dfi_alert_n_w4]
      dfi_rddata_w4: [phy_core_inst, dfi_rddata_w4]
      dfi_rddata_valid_w4: [phy_core_inst, dfi_rddata_valid_w4]

      dfi_alert_n_w5: [phy_core_inst, dfi_alert_n_w5]
      dfi_rddata_w5: [phy_core_inst, dfi_rddata_w5]
      dfi_rddata_valid_w5: [phy_core_inst, dfi_rddata_valid_w5]

      dfi_alert_n_w6: [phy_core_inst, dfi_alert_n_w6]
      dfi_rddata_w6: [phy_core_inst, dfi_rddata_w6]
      dfi_rddata_valid_w6: [phy_core_inst, dfi_rddata_valid_w6]

      dfi_alert_n_w7: [phy_core_inst, dfi_alert_n_w7]
      dfi_rddata_w7: [phy_core_inst, dfi_rddata_w7]
      dfi_rddata_valid_w7: [phy_core_inst, dfi_rddata_valid_w7]

    phy_core_inst:
      clk_ext: clk100
      rst_ext: user_btn0

      serial_rx: serial2_rx
      serial_tx: serial2_tx

      ddram_dq: lpddr4_dq
      ddram_dqs_p: lpddr4_dqs_p
      ddram_dqs_n: lpddr4_dqs_n
      ddram_dmi: lpddr4_dmi
      ddram_clk_p: lpddr4_clk_p
      ddram_clk_n: lpddr4_clk_n
      ddram_cke: lpddr4_cke
      ddram_odt: lpddr4_odt
      ddram_reset_n: lpddr4_reset_n
      ddram_cs: lpddr4_cs
      ddram_ca: lpddr4_ca

      dfi_init_start: [dram_ctrl_inst, dfi_init_start]

      dfi_cke_p0: [dram_ctrl_inst, dfi_cke_p0]
      dfi_reset_n_p0: [dram_ctrl_inst, dfi_reset_n_p0]
      dfi_mode_2n_p0: [dram_ctrl_inst, dfi_mode_2n_p0]
      dfi_address_p0: [dram_ctrl_inst, dfi_address_p0]
      dfi_bank_p0: [dram_ctrl_inst, dfi_bank_p0]
      dfi_cas_n_p0: [dram_ctrl_inst, dfi_cas_n_p0]
      dfi_cs_n_p0: [dram_ctrl_inst, dfi_cs_n_p0]
      dfi_ras_n_p0: [dram_ctrl_inst, dfi_ras_n_p0]
      dfi_act_n_p0: [dram_ctrl_inst, dfi_act_n_p0]
      dfi_odt_p0: [dram_ctrl_inst, dfi_odt_p0]
      dfi_we_n_p0: [dram_ctrl_inst, dfi_we_n_p0]
      dfi_wrdata_p0: [dram_ctrl_inst, dfi_wrdata_p0]
      dfi_wrdata_en_p0: [dram_ctrl_inst, dfi_wrdata_en_p0]
      dfi_wrdata_mask_p0: [dram_ctrl_inst, dfi_wrdata_mask_p0]
      dfi_rddata_en_p0: [dram_ctrl_inst, dfi_rddata_en_p0]

      dfi_cke_p1: [dram_ctrl_inst, dfi_cke_p1]
      dfi_reset_n_p1: [dram_ctrl_inst, dfi_reset_n_p1]
      dfi_mode_2n_p1: [dram_ctrl_inst, dfi_mode_2n_p1]
      dfi_address_p1: [dram_ctrl_inst, dfi_address_p1]
      dfi_bank_p1: [dram_ctrl_inst, dfi_bank_p1]
      dfi_cas_n_p1: [dram_ctrl_inst, dfi_cas_n_p1]
      dfi_cs_n_p1: [dram_ctrl_inst, dfi_cs_n_p1]
      dfi_ras_n_p1: [dram_ctrl_inst, dfi_ras_n_p1]
      dfi_act_n_p1: [dram_ctrl_inst, dfi_act_n_p1]
      dfi_odt_p1: [dram_ctrl_inst, dfi_odt_p1]
      dfi_we_n_p1: [dram_ctrl_inst, dfi_we_n_p1]
      dfi_wrdata_p1: [dram_ctrl_inst, dfi_wrdata_p1]
      dfi_wrdata_en_p1: [dram_ctrl_inst, dfi_wrdata_en_p1]
      dfi_wrdata_mask_p1: [dram_ctrl_inst, dfi_wrdata_mask_p1]
      dfi_rddata_en_p1: [dram_ctrl_inst, dfi_rddata_en_p1]

      dfi_cke_p2: [dram_ctrl_inst, dfi_cke_p2]
      dfi_reset_n_p2: [dram_ctrl_inst, dfi_reset_n_p2]
      dfi_mode_2n_p2: [dram_ctrl_inst, dfi_mode_2n_p2]
      dfi_address_p2: [dram_ctrl_inst, dfi_address_p2]
      dfi_bank_p2: [dram_ctrl_inst, dfi_bank_p2]
      dfi_cas_n_p2: [dram_ctrl_inst, dfi_cas_n_p2]
      dfi_cs_n_p2: [dram_ctrl_inst, dfi_cs_n_p2]
      dfi_ras_n_p2: [dram_ctrl_inst, dfi_ras_n_p2]
      dfi_act_n_p2: [dram_ctrl_inst, dfi_act_n_p2]
      dfi_odt_p2: [dram_ctrl_inst, dfi_odt_p2]
      dfi_we_n_p2: [dram_ctrl_inst, dfi_we_n_p2]
      dfi_wrdata_p2: [dram_ctrl_inst, dfi_wrdata_p2]
      dfi_wrdata_en_p2: [dram_ctrl_inst, dfi_wrdata_en_p2]
      dfi_wrdata_mask_p2: [dram_ctrl_inst, dfi_wrdata_mask_p2]
      dfi_rddata_en_p2: [dram_ctrl_inst, dfi_rddata_en_p2]

      dfi_cke_p3: [dram_ctrl_inst, dfi_cke_p3]
      dfi_reset_n_p3: [dram_ctrl_inst, dfi_reset_n_p3]
      dfi_mode_2n_p3: [dram_ctrl_inst, dfi_mode_2n_p3]
      dfi_address_p3: [dram_ctrl_inst, dfi_address_p3]
      dfi_bank_p3: [dram_ctrl_inst, dfi_bank_p3]
      dfi_cas_n_p3: [dram_ctrl_inst, dfi_cas_n_p3]
      dfi_cs_n_p3: [dram_ctrl_inst, dfi_cs_n_p3]
      dfi_ras_n_p3: [dram_ctrl_inst, dfi_ras_n_p3]
      dfi_act_n_p3: [dram_ctrl_inst, dfi_act_n_p3]
      dfi_odt_p3: [dram_ctrl_inst, dfi_odt_p3]
      dfi_we_n_p3: [dram_ctrl_inst, dfi_we_n_p3]
      dfi_wrdata_p3: [dram_ctrl_inst, dfi_wrdata_p3]
      dfi_wrdata_en_p3: [dram_ctrl_inst, dfi_wrdata_en_p3]
      dfi_wrdata_mask_p3: [dram_ctrl_inst, dfi_wrdata_mask_p3]
      dfi_rddata_en_p3: [dram_ctrl_inst, dfi_rddata_en_p3]

      dfi_cke_p4: [dram_ctrl_inst, dfi_cke_p4]
      dfi_reset_n_p4: [dram_ctrl_inst, dfi_reset_n_p4]
      dfi_mode_2n_p4: [dram_ctrl_inst, dfi_mode_2n_p4]
      dfi_address_p4: [dram_ctrl_inst, dfi_address_p4]
      dfi_bank_p4: [dram_ctrl_inst, dfi_bank_p4]
      dfi_cas_n_p4: [dram_ctrl_inst, dfi_cas_n_p4]
      dfi_cs_n_p4: [dram_ctrl_inst, dfi_cs_n_p4]
      dfi_ras_n_p4: [dram_ctrl_inst, dfi_ras_n_p4]
      dfi_act_n_p4: [dram_ctrl_inst, dfi_act_n_p4]
      dfi_odt_p4: [dram_ctrl_inst, dfi_odt_p4]
      dfi_we_n_p4: [dram_ctrl_inst, dfi_we_n_p4]
      dfi_wrdata_p4: [dram_ctrl_inst, dfi_wrdata_p4]
      dfi_wrdata_en_p4: [dram_ctrl_inst, dfi_wrdata_en_p4]
      dfi_wrdata_mask_p4: [dram_ctrl_inst, dfi_wrdata_mask_p4]
      dfi_rddata_en_p4: [dram_ctrl_inst, dfi_rddata_en_p4]

      dfi_cke_p5: [dram_ctrl_inst, dfi_cke_p5]
      dfi_reset_n_p5: [dram_ctrl_inst, dfi_reset_n_p5]
      dfi_mode_2n_p5: [dram_ctrl_inst, dfi_mode_2n_p5]
      dfi_address_p5: [dram_ctrl_inst, dfi_address_p5]
      dfi_bank_p5: [dram_ctrl_inst, dfi_bank_p5]
      dfi_cas_n_p5: [dram_ctrl_inst, dfi_cas_n_p5]
      dfi_cs_n_p5: [dram_ctrl_inst, dfi_cs_n_p5]
      dfi_ras_n_p5: [dram_ctrl_inst, dfi_ras_n_p5]
      dfi_act_n_p5: [dram_ctrl_inst, dfi_act_n_p5]
      dfi_odt_p5: [dram_ctrl_inst, dfi_odt_p5]
      dfi_we_n_p5: [dram_ctrl_inst, dfi_we_n_p5]
      dfi_wrdata_p5: [dram_ctrl_inst, dfi_wrdata_p5]
      dfi_wrdata_en_p5: [dram_ctrl_inst, dfi_wrdata_en_p5]
      dfi_wrdata_mask_p5: [dram_ctrl_inst, dfi_wrdata_mask_p5]
      dfi_rddata_en_p5: [dram_ctrl_inst, dfi_rddata_en_p5]

      dfi_cke_p6: [dram_ctrl_inst, dfi_cke_p6]
      dfi_reset_n_p6: [dram_ctrl_inst, dfi_reset_n_p6]
      dfi_mode_2n_p6: [dram_ctrl_inst, dfi_mode_2n_p6]
      dfi_address_p6: [dram_ctrl_inst, dfi_address_p6]
      dfi_bank_p6: [dram_ctrl_inst, dfi_bank_p6]
      dfi_cas_n_p6: [dram_ctrl_inst, dfi_cas_n_p6]
      dfi_cs_n_p6: [dram_ctrl_inst, dfi_cs_n_p6]
      dfi_ras_n_p6: [dram_ctrl_inst, dfi_ras_n_p6]
      dfi_act_n_p6: [dram_ctrl_inst, dfi_act_n_p6]
      dfi_odt_p6: [dram_ctrl_inst, dfi_odt_p6]
      dfi_we_n_p6: [dram_ctrl_inst, dfi_we_n_p6]
      dfi_wrdata_p6: [dram_ctrl_inst, dfi_wrdata_p6]
      dfi_wrdata_en_p6: [dram_ctrl_inst, dfi_wrdata_en_p6]
      dfi_wrdata_mask_p6: [dram_ctrl_inst, dfi_wrdata_mask_p6]
      dfi_rddata_en_p6: [dram_ctrl_inst, dfi_rddata_en_p6]

      dfi_cke_p7: [dram_ctrl_inst, dfi_cke_p7]
      dfi_reset_n_p7: [dram_ctrl_inst, dfi_reset_n_p7]
      dfi_mode_2n_p7: [dram_ctrl_inst, dfi_mode_2n_p7]
      dfi_address_p7: [dram_ctrl_inst, dfi_address_p7]
      dfi_bank_p7: [dram_ctrl_inst, dfi_bank_p7]
      dfi_cas_n_p7: [dram_ctrl_inst, dfi_cas_n_p7]
      dfi_cs_n_p7: [dram_ctrl_inst, dfi_cs_n_p7]
      dfi_ras_n_p7: [dram_ctrl_inst, dfi_ras_n_p7]
      dfi_act_n_p7: [dram_ctrl_inst, dfi_act_n_p7]
      dfi_odt_p7: [dram_ctrl_inst, dfi_odt_p7]
      dfi_we_n_p7: [dram_ctrl_inst, dfi_we_n_p7]
      dfi_wrdata_p7: [dram_ctrl_inst, dfi_wrdata_p7]
      dfi_wrdata_en_p7: [dram_ctrl_inst, dfi_wrdata_en_p7]
      dfi_wrdata_mask_p7: [dram_ctrl_inst, dfi_wrdata_mask_p7]
      dfi_rddata_en_p7: [dram_ctrl_inst, dfi_rddata_en_p7]

external:
  ports:
    in:
      - clk100
      - user_btn0
      - serial1_rx
      - serial2_rx
      - lpddr4_dq
      - lpddr4_dqs_p
      - lpddr4_dqs_n
      - lpddr4_dmi
    out:
      - user_led0
      - user_led1
      - user_led2
      - user_led3
      - user_led4
      - serial1_tx
      - serial2_tx
      - lpddr4_clk_p
      - lpddr4_clk_n
      - lpddr4_cke
      - lpddr4_odt
      - lpddr4_reset_n
      - lpddr4_cs
      - lpddr4_ca
